### ISSUE TITLE
Issues Building App

### ISSUE THREAD

**Issue by justinhancock77** [Hamad-Anwar/Task-Sync-Pro-Flutter#1]
Hello, 

This looks beautiful and I'm anxious to try it out.  I am relatively new to flutter and dart, so I could be wrong here, but it appears that there are some issues / inconsistencies in the readme.

1.  There is no pubspec.yaml.  Could you add it to this repository?
2.  There is no 'task-scheduler-app folder to cd into.

Thanks in advance for any assistance!

**Comment by Hamad-Anwar** [comment]
I'll add the pubspec later, and the 'task-scheduler-app' directory name within the project might be changed.
